package com.app.core.inuha.views.quanly.components.table.soluongton;

import com.app.core.inuha.views.quanly.components.table.trangthai.*;
import com.app.utils.ColorUtils;
import com.app.utils.ProductUtils;

/**
 *
 * @author inuHa
 */
public class InuhaSoLuongTonSanPhamTablePanel extends javax.swing.JPanel {

    /** Creates new form InuhaTrangThaiSanPhamTablePanel */
    public InuhaSoLuongTonSanPhamTablePanel() {
	initComponents();
    }
    
    public InuhaSoLuongTonSanPhamTablePanel(int soLuong) {
	this();
	setSoLuong(soLuong);
    }
    
    public void setSoLuong(int soLuong) { 
	txtText.setText(String.valueOf(soLuong));
	if (soLuong > 0) {
	    txtText.setForeground(ColorUtils.PRIMARY_TEXT);
	} else {
	    txtText.setText("Hết hàng");
	    txtText.setForeground(ColorUtils.DANGER_COLOR);
	}
    }
   
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtText = new javax.swing.JLabel();

        txtText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtText.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtText, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtText, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtText;
    // End of variables declaration//GEN-END:variables

}
