/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.app.core.inuha.views.quanly.components.table.nhanvien;

import com.app.core.inuha.views.quanly.components.table.trangthai.*;
import com.app.utils.ColorUtils;
import com.app.utils.ProductUtils;
import com.app.utils.SessionUtils;

/**
 *
 * @author inuHa
 */
public class InuhaTrangThaiNhanVienTablePanel extends javax.swing.JPanel {

    /** Creates new form InuhaTrangThaiSanPhamTablePanel */
    public InuhaTrangThaiNhanVienTablePanel() {
	initComponents();
    }
    
    public InuhaTrangThaiNhanVienTablePanel(boolean trangThai) {
	this();
	setTrangThai(trangThai);
    }
    
    public void setTrangThai(boolean trangThai) {
	txtText.setText(SessionUtils.getTrangThai(trangThai));
	if (trangThai) {
	    txtText.setForeground(ColorUtils.SUCCESS_COLOR);
	} else {
	    txtText.setForeground(ColorUtils.DANGER_COLOR);
	}
    }
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtText = new javax.swing.JLabel();

        txtText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtText.setText("Ngừng bán");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtText, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtText, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtText;
    // End of variables declaration//GEN-END:variables

}
